baseURL = "http://yulab-smu.top"
title = "YuLab@SMU"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "YuLab-SMU"
    description = "Research group led by Prof. Guangchuang Yu in School of Basic Medical Sciences, Southern Medical University"
    keywords = "developer,bioinformatics,omics,visualization"
    info = "Bioinformagician @ SMU"
    avatarURL = "images/gc.png"
    #gravatar = "john.doe@example.com"
    footerContent = "You are welcome to join us."

    dateFormat = "September 1, 2018"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = true #false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "ABCDE"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
#[params.plausibleAnalytics]
#    domain = "example.com"
#    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/YuLab-SMU/"
[[params.social]]
    name = "微信公众号"
    icon = "fa fa-wechat"
    weight = 3
    url = "images/biobabble.jpg"
#[[params.social]]
#    name = "LinkedIn"
#    icon = "fa fa-linkedin"
#    weight = 4
#    url = "https://www.linkedin.com/in/johndoe/"
#[[params.social]]
#    name = "Medium"
#    icon = "fa fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"
#[[params.social]]
#    name = "RSS"
#    icon = "fa fa-rss"
#    weight = 6
#    url = "https://yulab-smu.top/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Publications"
            weight = 2
            url = "publications/"

            [[languages.en.menu.main]]
            name = "Achievements"
            weight = 3
            url = "achievements/"

            [[languages.en.menu.main]]
            name = "Software"
            weight = 4
            url = "software/"

            [[languages.en.menu.main]]
            name = "Members"
            weight = 5
            url = "members/"

##            [[languages.en.menu.main]]
##            name = "Documents"
##            weight = 6
##            url = "documents/"

            [[languages.en.menu.main]]
            name = "News"
            weight = 7
            url = "news/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 8
            url = "contact/"


#    [languages.pt-br]
#        languageName = "Português"
#        title = "João Ninguém"
#
#        [languages.pt-br.params]
#            author = "João Ninguém"
#            info = "Full Stack DevOps e Mágico"
#            description = "Sítio pessoal de João Ninguém"
#            keywords = "blog,desenvolvedor,pessoal"
#            footerContent = "Coloque algum texto aqui."
#
#        [languages.pt-br.menu]
#
#            [[languages.pt-br.menu.main]]
#            name = "Sobre"
#            weight = 1
#            url = "about/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Projetos"
#            weight = 3
#            url = "projects/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Contato"
#            weight = 5
#            url = "contact/"
